Repository zero-to-mastery/ascii-art, pull requests merged in 2024-10, with the labels that each got.

#182 adds back in functionality to print image
  community-version.py
Labels: hacktoberfest-accepted

#184 Add Advanced ASCII Art Generator with Color and Filter Options
  FEATURES.md
  USAGE.md
  community-version.py
  requirements.txt
Labels: hacktoberfest-accepted

#191 resolves merge conflicts
  README.md
Labels: hacktoberfest-accepted

#192 add type hints in handle_image_conversion
  community-version.py
Labels: hacktoberfest-accepted

#199 feature/add-ascii-art-example
  README.md
Labels: hacktoberfest-accepted

#183 Added gui and rename community-version.py
  gui.py
  ztm-icon.ico
Labels: Change Requested, hacktoberfest-accepted

#186 added pointillism-art
  pointillism-art.py
  requirements.txt
Labels: Change Requested, hacktoberfest-accepted

#202 Samilabud add file path validation samilabud
  community-version.py
  output.txt
Labels: hacktoberfest-accepted

#203 Gowtham4545 master
  community-version.py
Labels: hacktoberfest-accepted

#195 Text to Ascii Image conversion
  community-version.py
Labels: Conflict Present

#200 Small Addition
  community-version.py
  example/makeArtPython3.py
Labels: hacktoberfest-accepted

#201 Added Grayscale Feature to Streamlit App
  example/ztm-logo_ascii_art.txt
Labels: hacktoberfest-accepted

#207 added geometric-art
  geometric-art.py
  requirements.txt
Labels: hacktoberfest-accepted

#212 added a contours selection feature
  community-version.py
  output.txt
Labels: Change Requested, hacktoberfest-accepted

#240 added pattern numeric
  community-version.py
Labels: hacktoberfest-accepted

#234 Add texture-art
  texture-art-source/README.md
  texture-art-source/p1.jpg
  texture-art-source/p2.jpg
  texture-art-source/p3.jpg
  texture-art-source/p4.jpg
  texture-art-source/p5.jpg
  texture-art.py
Labels: hacktoberfest-accepted

#241 conditional to display contents of output into the CLI if colorize==False
  community-version.py
Labels: hacktoberfest-accepted

#246 added ascii-art-matrix-effect with color changing
  ascii-art-matrix-effect-color.py
Labels: hacktoberfest-accepted

#247 New Feature Added : Defining own custom ascii characters
  community-version.py
Labels: hacktoberfest-accepted

#248 feat: add a new script using gradio
  gradio_ascii_art.py
  output.txt
  requirements.txt
Labels: hacktoberfest-accepted

#249 chore: add ruff linter formatter
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  FEATURES.md
  README.md
  pyproject.toml
  requirements.txt
Labels: Change Requested, hacktoberfest-accepted

#253 Update fast-api-main.py
  fast-api-main.py
Labels: hacktoberfest-accepted

#255 Add invert-color-art
  invert-color-art.py
Labels: hacktoberfest-accepted

#256 added the feature of animating the ASCII Art
  community-version.py
Labels: hacktoberfest-accepted

#257 Abhinav 0103 rangeblur
  community-version.py
Labels: hacktoberfest-accepted

#237 Added a Gaussian Blur with variable range
  community-version.py
Labels: Conflict Present, Change Requested

#258 Abhinav 0103 rangesharpen
  community-version.py
  output.txt
Labels: hacktoberfest-accepted

#213 Added Live Video Stream ASCII Art conversion
  community-version.py
Labels: Change Requested, hacktoberfest-accepted
